kai:
	cd ../.. ; ${MAKE} kai

kaibib:
	cd ../.. ; ${MAKE} kaibib

newpdf:
	cd ../.. ; ${MAKE} newpdf

pdf:
	cd ../.. ; ${MAKE} pdf

quick:
	cd ../.. ; ${MAKE} quick

clean:
	cd ../.. ; ${MAKE} clean

veryclean:
	cd ../.. ; ${MAKE} veryclean

localbib:
	cd ../.. ; ${MAKE} localbib
