default:
	cd .. ; ${MAKE}

kai:
	cd .. ; ${MAKE} kai

localbib:
	cd .. ; ${MAKE} localbib

newpdf:
	cd .. ; ${MAKE} newpdf

kaibib:
	cd .. ; ${MAKE} kaibib

quick:
	cd .. ; ${MAKE} quick

clean:
	cd .. ; ${MAKE} clean
